basePath: /api/v0
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8081
info:
  contact:
    email: info@skypier.io
    name: Skypier info
    url: http://skypier.io/
  description: This is a Skypier VPN REST API.
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
  title: Swagger Skypier API
  version: "1.0"
paths:
  /getConfig:
    get:
      description: Get the content of the configuration file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get the configuration
      tags:
      - config
swagger: "2.0"
