name: Create Cross Platoform Releases

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64', '386', 'arm64' ]
        os: ['linux', 'windows', 'darwin']
        exclude:
          - arch: 386
            os: darwin

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o skypier-vpn -ldflags "-s -w" -trimpath
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: Skypier-VPN-${{ matrix.os }}-${{ matrix.arch }}
          path: skypier-vpn
